services:
  badgehub-direct:
    build: ../..
    ports:
      - "${EXPOSED_PORT}:8081"
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      CATEGORY_NAMES: ${CATEGORY_NAMES}
      ADMIN_CATEGORY_NAMES: ${ADMIN_CATEGORY_NAMES}
      BADGE_SLUGS: ${BADGE_SLUGS}
      BADGEHUB_API_BASE_URL: ${BADGEHUB_API_BASE_URL}
      DB_BADGEHUB_API_BASE_URL: ${DB_BADGEHUB_API_BASE_URL}
      MAX_UPLOAD_FILE_SIZE_BYTES: ${MAX_UPLOAD_FILE_SIZE_BYTES}
      REFRESH_REPORTS_INTERVAL_SEC: ${REFRESH_REPORTS_INTERVAL_SEC}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWD: ${MQTT_PASSWD}
      MQTT_TOPIC: ${MQTT_TOPIC}
      MQTT_SERVER: ${MQTT_SERVER}
      MQTT_INTERVAL_SEC: ${MQTT_INTERVAL_SEC}
    networks:
      - badgehub_network
networks:
  badgehub_network:
    name: badgehub_network
    external: true
